
scheme: Pisces
darkmode: true
theme_color:
  light: 'mediumpurple' 
  dark: 'mediumpurple' 

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg
  # android_manifest: /images/manifest.json

# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  # head: source/_data/head.njk
  # header: source/_data/header.njk
  # sidebar: source/_data/sidebar.njk
  # postMeta: source/_data/post-meta.njk
  # postBodyStart: source/_data/post-body-start.njk
  # postBodyEnd: source/_data/post-body-end.njk
  # footer: source/_data/footer.njk
  # bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  # mixin: source/_data/mixins.styl
  style: source/_data/styles.styl

# sidebar
menu:
  home: / || fa fa-home
  分类:
    default: /categories/ || fa fa-th
    real: real/ || fa fa-user
    virt: virt/ || fa fa-mouse-pointer
    fict: fict/ || fa fa-pencil
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-solid fa-feather-pointed
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

social:
  GitHub: https://github.com/geezmolycos || fab fa-github
  Bilibili: https://space.bilibili.com/49868114 || fa-brands fa-bilibili
  E-Mail: 'javascript:alert("请看「关于」页面") || fa fa-envelope'

# footer
footer:
  since: 2023
  icon:
    name: fa fa-solid fa-feather-pointed
    color: '#c60'

# Disable animation
motion:
  enable: false

# image viewer
fancybox: true

math:
  katex:
    enable: true

note:
  style: simple
  icons: true

vendors:
  internal: cdnjs

# Set the text alignment in the posts.
text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: start
  mobile: start

# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false
