
scheme: Pisces
darkmode: true
theme_color:
  light: "#c60"
  dark: "#c60"

# Disable animation
motion:
  enable: false

# image viewer
fancybox: true

math:
  katex:
    enable: true

note:
  style: simple

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg
  # android_manifest: /images/manifest.json

# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  # head: source/_data/head.njk
  # header: source/_data/header.njk
  # sidebar: source/_data/sidebar.njk
  # postMeta: source/_data/post-meta.njk
  # postBodyStart: source/_data/post-body-start.njk
  # postBodyEnd: source/_data/post-body-end.njk
  # footer: source/_data/footer.njk
  # bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  # mixin: source/_data/mixins.styl
  style: source/_data/styles.styl

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat
